server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/pricepilot
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# Scraper
scraper.timeout-ms=10000

# Free scraping API for MVP testing
scraperapi.api.key=${SCRAPERAPI_KEY:}
scraperapi.api.url=http://api.scraperapi.com